### ISSUE TITLE
authcode request permanent

### ISSUE THREAD

**Issue by hugocrank** [KoenZomers/RingSnapshotDownload#13]
Hello, I have written a batch in which I retrieve an image every 60 seconds with forceupdate. unfortunately, after about 10 snapshots I always get the 2-factor query for the code again. am I querying too often? can I solve it differently?

**Comment by scholzmichael** [comment]
Happened to me as well with all versions >1.3, this is why I kept version 1.3 until it stopped working now due to api changes...

**Comment by hugocrank** [comment]
it is not working since 1 week.. i cant download any snapshots. i become an message like:
`Connecting to Ring services
Authenticating using refresh token from previous session
Unhandled exception. System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte )
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte )
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo , Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo )
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at KoenZomers.Ring.Api.Session.RefreshSession(String refreshToken)
   at KoenZomers.Ring.Api.Session.GetSessionByRefreshToken(String refreshToken)
   at KoenZomers.Ring.SnapshotDownload.Program.Main(String[] args)
   at KoenZomers.Ring.SnapshotDownload.Program.<Main>(String[] args)
`

**Comment by scholzmichael** [comment]
Allready stated the problem here: [https://github.com/KoenZomers/RingSnapshotDownload/issues/7](url) and here [https://github.com/KoenZomers/RingApi/issues/31#issuecomment-2010055782](url)

**Comment by scholzmichael** [comment]
Just tried V3.000, and the problem still persists, Authentication via 2FA requested by ring (received an SMS) after approx. 30 minutes. Since everything here is automated via crontab (downloading images from 5 cameras every 5 minutes) this will eventually lead to being locked out from ring for a while....had that before
Hint: this problem accured in all versions >V1.3 I tested.

**Comment by scholzmichael** [comment]
further analysis:

using the "watch" comand I started the output of a fresh image every 60 seconds with
sudo watch -n60 "./RingSnapshotDownload -username XXX.XXX@XXX.XX -password XXXXXXXXX -deviceid XXX80253X -forceupdate -out Haustuere"

 and received good case for more than 45 minutes:

Ring Snapshot Download Tool v3.0.0.0 by Koen Zomers

Using settings from /home/pi/Ring/Settings.json
Connecting to Ring services
Authenticating using refresh token from previous session
Requesting Ring device to capture a new snapshot
Refreshing session, Token expired at 01.01.0001 00:00:00
Refreshing session, Token expired at 01.01.0001 00:00:00
Downloading snapshot from Ring device with ID XXX80253X... Refreshing session, T
oken expired at 01.01.0001 00:00:00
OK
Saving image to Haustuere/XXX80253X - 2025-02-27 10-19-17.jpg... OK
Done

no problem so far, I then reduced the time to 10 seconds':

 sudo watch -n10 "./RingSnapshotDownload -username XXX.XXX@XXX.XX -password XXXXXXXXX -deviceid XXX80253X -forceupdate -out Haustuere"

after successfully pulling 12 images I get the following:

Using settings from /home/pi/Ring/Settings.json
Connecting to Ring services
Authenticating using refresh token from previous session
Requesting Ring device to capture a new snapshot
Unhandled exception. KoenZomers.Ring.Api.Exceptions.SessionNotAuthenticatedException: This
session has not yet been authenticated. Please call Authenticate() first.
   at KoenZomers.Ring.Api.Session.EnsureSessionValid()
   at KoenZomers.Ring.Api.Session.UpdateSnapshot(Int32 doorbotId)
   at KoenZomers.Ring.SnapshotDownload.Program.Main(String[] args)
   at KoenZomers.Ring.SnapshotDownload.Program.<Main>(String[] args)
Aborted

after that I did receive the 6 digit authentication code from ring and manually requesting a snapshot with

sudo ./RingSnapshotDownload -username XXX.XXX@XXX.XX -password XXXXXXXXX -deviceid XXX80253X -forceupdate -out Haustuere

 showed:

Using settings from /home/pi/Ring/Settings.json
Connecting to Ring services
Authenticating using provided username and password
Two factor authentication enabled on this account, please enter the Ring token from the e-mail, text message or authenticator app:
XXXXXX _(I did enter the code)_
Requesting Ring device to capture a new snapshot
Refreshing session, Token expired at 01.01.0001 00:00:00
Refreshing session, Token expired at 01.01.0001 00:00:00
Downloading snapshot from Ring device with ID XXX80253X... Refreshing session, Token expired at 01.01.0001 00:00:00
OK
Saving image to Haustuere/XXX80253X - 2025-02-27 10-44-45.jpg... OK
Done

so it clearly seems to be a timing issue, since I'm usually calling 5 images every 5 minutes the authentication request comes after approx. 30 minutes...

could it be that the token gets corruppted within the "settings.json" after an unhandled exception?
